# Generated by Django 3.0.5 on 2020-05-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOK', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
